const POSTGRES_USERS_TABLE = "users";
const POSTGRES_PENDING_USERS_TABLE = "pending_users";
const POSTGRES_TOKEN_OTPS_TABLE = "token_otps";
const POSTGRES_OUTBOX_EVENTS_TABLE = "outbox_events";
const POSTGRES_API_KEYS_TABLE = "api_keys";

const POSTGRES_CREATE_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  auth_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_PENDING_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_PENDING_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT NULL,
  email TEXT NULL,
  password TEXT NULL,
  trace_id TEXT,
  parent_span_id TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_TOKEN_OTPS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_TOKEN_OTPS_TABLE} (
  id TEXT PRIMARY KEY,
  token TEXT NOT NULL,
  otp TEXT NOT NULL,
  token_type TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_OUTBOX_EVENTS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_OUTBOX_EVENTS_TABLE} (
  id TEXT PRIMARY KEY,
  topic TEXT NOT NULL,
  idempotency_id TEXT NOT NULL,
  key TEXT,
  data JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMP
);
`;

const POSTGRES_CREATE_API_KEYS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_API_KEYS_TABLE} (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES ${POSTGRES_USERS_TABLE}(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  key_val TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMP,
  revoked_at TIMESTAMP
);
`;

const POSTGRES_ALTER_API_KEYS_ADD_KEY_VAL = `
ALTER TABLE ${POSTGRES_API_KEYS_TABLE} ADD COLUMN IF NOT EXISTS key_val TEXT;
`;

export const POSTGRES_SCHEMA_STATEMENTS = [
  POSTGRES_CREATE_USERS_TABLE,
  POSTGRES_CREATE_PENDING_USERS_TABLE,
  POSTGRES_CREATE_TOKEN_OTPS_TABLE,
  POSTGRES_CREATE_OUTBOX_EVENTS_TABLE,
  POSTGRES_CREATE_API_KEYS_TABLE,
  POSTGRES_ALTER_API_KEYS_ADD_KEY_VAL,
];
