const POSTGRES_USERS_TABLE = "users";
const POSTGRES_PENDING_USERS_TABLE = "pending_users";
const POSTGRES_TOKEN_OTPS_TABLE = "token_otps";

const POSTGRES_CREATE_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_PENDING_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_PENDING_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_TOKEN_OTPS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_TOKEN_OTPS_TABLE} (
  id TEXT PRIMARY KEY,
  token TEXT NOT NULL,
  otp TEXT NOT NULL,
  token_type TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

export const POSTGRES_SCHEMA_STATEMENTS = [
  POSTGRES_CREATE_USERS_TABLE,
  POSTGRES_CREATE_PENDING_USERS_TABLE,
  POSTGRES_CREATE_TOKEN_OTPS_TABLE,
] as const;
