const POSTGRES_USERS_TABLE = "users";
const POSTGRES_PENDING_USERS_TABLE = "pending_users";
const POSTGRES_TOKEN_OTPS_TABLE = "token_otps";
const POSTGRES_OUTBOX_EVENTS_TABLE = "outbox_events";

const POSTGRES_CREATE_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_PENDING_USERS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_PENDING_USERS_TABLE} (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  trace_id TEXT,
  parent_span_id TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_TOKEN_OTPS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_TOKEN_OTPS_TABLE} (
  id TEXT PRIMARY KEY,
  token TEXT NOT NULL,
  otp TEXT NOT NULL,
  token_type TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
`;

const POSTGRES_CREATE_OUTBOX_EVENTS_TABLE = `
CREATE TABLE IF NOT EXISTS ${POSTGRES_OUTBOX_EVENTS_TABLE} (
  id TEXT PRIMARY KEY,
  topic TEXT NOT NULL,
  idempotency_id TEXT NOT NULL,
  key TEXT,
  data TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMP
);
`;

export const POSTGRES_SCHEMA_STATEMENTS = [
  POSTGRES_CREATE_USERS_TABLE,
  POSTGRES_CREATE_PENDING_USERS_TABLE,
  POSTGRES_CREATE_TOKEN_OTPS_TABLE,
  POSTGRES_CREATE_OUTBOX_EVENTS_TABLE,
  "ALTER TABLE pending_users ADD COLUMN IF NOT EXISTS trace_id TEXT;",
  "ALTER TABLE pending_users ADD COLUMN IF NOT EXISTS parent_span_id TEXT;",
] as const;
